version: "3.5"

services:
  web:
    build: './php_nginx/'
    working_dir: /app
    ports:
      - 80:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: 'postgres'
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: alyz
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root

  adminer:
    image: 'adminer:4.7'
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgresql:
